# Generated by Django 3.2.12 on 2022-08-16 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_BACKEND', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='role_creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 16, 14, 23, 33, 150367)),
        ),
    ]
