# Generated by Django 3.2.12 on 2022-08-09 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_BACKEND', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='associated_project',
            new_name='project_id',
        ),
        migrations.DeleteModel(
            name='report',
        ),
    ]
