# Generated by Django 3.2.12 on 2022-08-16 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_BACKEND', '0002_role_role_creation_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tasks',
            new_name='task',
        ),
        migrations.AlterField(
            model_name='role',
            name='role_creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 16, 14, 34, 6, 435931)),
        ),
    ]
