# Generated by Django 3.2.12 on 2022-08-16 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_BACKEND', '0003_auto_20220816_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_creation_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
