# Generated by Django 3.2.12 on 2022-08-09 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_BACKEND', '0003_tasks_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
