# Generated by Django 3.2.12 on 2022-08-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_BACKEND', '0005_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='project_start_date',
            field=models.DateField(),
        ),
    ]
